spring.profiles.active=test
spring.jpa.open-in-view=true


spring.docker.compose.enabled=false
spring.autoconfigure.exclude=org.springframework.ai.model.google.genai.autoconfigure.chat.GoogleGenAiChatAutoConfiguration
