spring.profiles.active=test
spring.jpa.open-in-view=true

spring.docker.compose.enabled=false

app.crypto.secret=${SECRET:0123456789abcdef0123456789abcdef}
app.jwt.secret=${JWT_SECRET:0123456789abcdef0123456789abcdef}
app.jwt.expirationMs=86400000

